### PR TITLE
apiconnect hoc

### PR DESCRIPTION
**Pull request by paolommj**
todos

- [x] document use case
- [ ]  draw a sample flow

### CODE REVIEW

**Comment by paolommj** [comment]
this might be ready to be merged and refined later on

**Review by donkyfronky — CHANGES_REQUESTED** [review]
I would like to see "getInitialProps" word on the line 14 of docs/apiConnect.md. Should be more clear to understand while learning.

**Review by donkyfronky — APPROVED** [review]

**Review by mogui — CHANGES_REQUESTED** [review]
Why the documentation is in a different file than the main readme, it's not so long.
At least put some basic example of using iit iin the main readme

**Comment by paolommj** [comment]
Usage is super simple but it's hard to explain why it is useful. I would like to sum up everything in the doc and this is just a brick. I think a good "first page doc" needs more time and i would like to release this bit.

**Review by mogui — APPROVED** [review]

**Pull request merged**
